os: linux
language: node_js
node_js: 15.10
install: npm i
before_script: npm run build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
